import type {Metadata} from "next";
import {Roboto} from "next/font/google";
import {Header} from "@app/components/shared/Header";
import {Footer} from "@app/components/shared/Footer";
import "../sass/main.scss";

const roboto= Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100","400", "700"],
})

export const metadata: Metadata = {
  title: "Store App",
  description: "Generated by Store App",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
